/// Flutter icons HandBook
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HandBook
///      fonts:
///       - asset: fonts/HandBook.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HandBook {
  HandBook._();

  static const _kFontFam = 'HandBook';
  static const _kFontPkg = null;

  static const IconData menu_book_black_24dp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
